nama    = input("Nama                   :")
nim     = input("Nim                    :")
paralel = input("Kelas Paralel          :")
ttl     = input("Tempat/Tanggal Lahir   :")
alamat  = input("Alamat                 :")
hobi    = input("Hobby                  :")
nohp    = input("No. HP                 :")
print("Nama                   :" + nama)
print("Nim                    :" + nim)
print("Kelas Paralel          :" + paralel)
print("Tempat/Tanggal Lahir   :" + ttl)
print("Alamat                 :" +alamat)
print("Hobby                  :" +hobi)
print("No. HP                 :" +nohp)